dev-python/pycurl: revert change due to pypy3 break
src/pycurl.h:698:31: error: ‘Py_TRASHCAN_END’ undeclared (first use in this function); did you mean ‘CPy_TRASHCAN_END’?
  698 | # define CPy_TRASHCAN_END(op) Py_TRASHCAN_END

so much for semver patch changes not having wildly breaking changes ...